<a href="https://colab.research.google.com/github/YASHYOGESHAHIRE/03-dividend-based-investment-finance/blob/main/dividendbasedinvesting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#We are using nifty fifty, but nifty fifty dont give that much divident, so atleast we should give 500 to 1000 other stocks

In [2]:
import pandas as pd
import numpy as np
import yfinance as yf
import math
from scipy import stats

In [3]:
tickers = pd.read_csv('/content/top_50_indian_stocks.csv')
tickers.head()

         Ticker               Company Name
0   RELIANCE.NS        Reliance Industries
1        TCS.NS  Tata Consultancy Services
2   HDFCBANK.NS                  HDFC Bank
3       INFY.NS                    Infosys
4  ICICIBANK.NS                 ICICI Bank

In [4]:
## Weighted Scoring Model for finding the final Score

In [8]:
def create_dividend_df(tickers):
  columns=[
      "Ticker",
      "Dividend Yield(%)",
      "Dividend Rate",
      "Payout Ratio(%)",
      "5 Year Avg Dividend Yield(%)",
      "Earning Growth(%)"
  ]
  dividend_df = pd.DataFrame(columns=columns)
  for stock in tickers:
    ticker = yf.Ticker(stock)
    info = ticker.info

    # Corrected dividend_yield logic to handle 0.0 values correctly
    dividend_yield_raw = info.get("dividendYield")
    dividend_yield = dividend_yield_raw * 100 if dividend_yield_raw is not None else np.nan

    # These calculations already handle np.nan correctly due to default value in .get()
    dividend_rate = info.get("dividendRate", np.nan)
    payout_ratio = info.get("payoutRatio", np.nan) * 100
    five_year_avg_dividend_yield = info.get("fiveYearAvgDividendYield", np.nan) * 100
    earning_growth = info.get("earningsGrowth", np.nan)

    dividend_df.loc[len(dividend_df)] = [stock,dividend_yield,dividend_rate,payout_ratio,five_year_avg_dividend_yield,earning_growth]

  # Normalization should be done AFTER the dataframe is fully populated, so moved outside the loop
  numeric_cols=[
      "Dividend Yield(%)",
      "Dividend Rate",
      "Payout Ratio(%)",
      "5 Year Avg Dividend Yield(%)",
      "Earning Growth(%)"
  ]
  weights = {
      "Dividend Yield(%) Normalised":0.2,
      "Dividend Rate Normalised":0.2,
      "Payout Ratio(%) Normalised":0.2,
      "5 Year Avg Dividend Yield(%) Normalised":0.2,
      "Earning Growth(%) Normalised":0.2
  }

  # Apply normalization after collecting all data
  for col in numeric_cols:
    # Check if there are non-NaN values to avoid division by zero if all values are NaN
    if not dividend_df[col].isnull().all():
        col_min = dividend_df[col].min()
        col_max = dividend_df[col].max()

        if col_max - col_min == 0: # Handle cases where all non-NaN values are the same
            dividend_df[col+" Normalised"] = 0.5 # Assign a neutral value like 0.5
        # Corrected column name from "Payout Ratio" to "Payout Ratio(%)"
        elif col == "Payout Ratio(%)": # Payout ratio might be inverse
            dividend_df[col+" Normalised"] = 1 - (dividend_df[col]-col_min)/(col_max-col_min)
        else:
            dividend_df[col+" Normalised"] = (dividend_df[col]-col_min)/(col_max-col_min)
    else:
        dividend_df[col+" Normalised"] = np.nan # If all values are NaN, normalized is also NaN

  return dividend_df

In [9]:
tickers_list = tickers["Ticker"].values.tolist()
dividend_df = create_dividend_df(tickers_list)
dividend_df

ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}

,Ticker,Dividend Yield(%),Dividend Rate,Payout Ratio(%),5 Year Avg Dividend Yield(%),Earning Growth(%),Dividend Yield(%) Normalised,Dividend Rate Normalised,Payout Ratio(%) Normalised,5 Year Avg Dividend Yield(%) Normalised,Earning Growth(%) Normalised
0,RELIANCE.NS,46.0,6.00,9.210000,44.0,-0.126,0.049238,0.034483,0.903083,0.047146,0.068275
1,TCS.NS,564.0,124.00,46.320000,149.0,0.122,0.656506,0.774295,0.512575,0.177419,0.091280
2,HDFCBANK.NS,174.0,13.00,21.760000,102.0,0.075,0.199297,0.078370,0.771020,0.119107,0.086920
3,INFY.NS,418.0,50.00,64.650000,240.0,0.118,0.485346,0.310345,0.319689,0.290323,0.090909
4,ICICIBANK.NS,87.0,11.00,14.710000,99.0,0.084,0.097304,0.065831,0.845207,0.115385,0.087755
5,HINDUNILVR.NS,207.0,44.00,95.030000,158.0,0.214,0.237984,0.272727,0.000000,0.188586,0.099814
6,SBIN.NS,177.0,17.35,17.440000,150.0,-0.031,0.202814,0.105643,0.816479,0.178660,0.077087
7,BAJFINANCE.NS,62.0,5.40,14.420000,24.0,0.214,0.067995,0.030721,0.848258,0.022333,0.099814
8,BHARTIARTL.NS,89.0,16.00,36.060002,80.0,-0.340,0.099648,0.097179,0.620541,0.091811,0.048423
9,ITC.NS,570.0,16.00,86.920000,372.0,-0.727,0.663540,0.097179,0.085341,0.454094,0.012523
10,KOTAKBANK.NS,13.0,0.50,2.580000,6.0,0.098,0.010551,0.000000,0.972851,0.000000,0.089054
11,ADANIENT.NS,4.0,1.30,1.710000,65.0,NaN,0.000000,0.005016,0.982006,0.073201,NaN
12,LT.NS,96.0,38.00,29.090000,91.0,-0.345,0.107855,0.235110,0.693886,0.105459,0.047959
13,HCLTECH.NS,831.0,96.00,88.010000,357.0,-0.002,0.969519,0.598746,0.073871,0.435484,0.079777
14,ASIANPAINT.NS,102.0,27.50,55.530000,87.0,0.693,0.114889,0.169279,0.415658,0.100496,0.144249
15,AXISBANK.NS,8.0,1.00,1.180000,103.0,0.064,0.004689,0.003135,0.987583,0.120347,0.085900
16,SUNPHARMA.NS,93.0,16.50,34.520000,93.0,0.256,0.104338,0.100313,0.636746,0.107940,0.103711
17,WIPRO.NS,857.0,17.00,87.580000,151.0,-0.016,1.000000,0.103448,0.078396,0.179901,0.078479
18,ULTRACEMCO.NS,71.0,77.50,27.930000,53.0,NaN,0.078546,0.482759,0.706093,0.058313,NaN
19,HDFCLIFE.NS,37.0,2.10,23.700000,31.0,0.041,0.038687,0.010031,0.750605,0.031017,0.083766
20,ONGC.NS,699.0,18.50,41.000000,511.0,0.478,0.814771,0.112853,0.568557,0.626551,0.124304
21,NTPC.NS,310.0,11.35,29.070000,336.0,-0.016,0.358734,0.068025,0.694097,0.409429,0.078479
22,POWERGRID.NS,429.0,12.25,44.750000,474.0,0.096,0.498242,0.073668,0.529096,0.580645,0.088868
23,TATAMOTORS.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,INDUSINDBK.NS,17.0,1.50,0.000000,54.0,NaN,0.015240,0.006270,1.000000,0.059553,NaN
25,ADANIGREEN.NS,NaN,NaN,0.000000,NaN,2.098,NaN,NaN,1.000000,NaN,0.274583
26,TITAN.NS,26.0,11.00,19.229999,27.0,0.351,0.025791,0.065831,0.797643,0.026055,0.112523
27,DIVISLAB.NS,45.0,30.00,31.010000,114.0,0.136,0.048066,0.184953,0.673682,0.133995,0.092579
28,TECHM.NS,344.0,51.00,83.040000,232.0,0.159,0.398593,0.316614,0.126171,0.280397,0.094712
29,MARUTI.NS,107.0,140.00,28.910000,80.0,-0.064,0.120750,0.874608,0.695780,0.091811,0.074026
30,COALINDIA.NS,457.0,22.00,52.320000,812.0,0.129,0.531067,0.134796,0.449437,1.000000,0.091929
31,BPCL.NS,678.0,20.00,37.200000,540.0,0.280,0.790152,0.122257,0.608545,0.662531,0.105937
32,JSWSTEEL.NS,55.0,7.10,3.070000,98.0,9.918,0.059789,0.041379,0.967694,0.114144,1.000000
33,DRREDDY.NS,63.0,8.00,15.560001,63.0,-0.862,0.069168,0.047022,0.836262,0.070720,0.000000
34,BAJAJFINSV.NS,8.0,1.30,1.640000,14.0,0.057,0.004689,0.005016,0.982742,0.009926,0.085250
35,ADANIPORTS.NS,41.0,7.50,12.020001,57.0,0.036,0.043376,0.043887,0.873514,0.063275,0.083302
36,CIPLA.NS,93.0,13.00,27.080000,48.0,-0.546,0.104338,0.078370,0.715037,0.052109,0.029314
37,BRITANNIA.NS,177.0,90.50,71.309996,172.0,0.211,0.202814,0.564263,0.249605,0.205955,0.099536
38,HAVELLS.NS,103.0,12.00,37.120000,59.0,0.396,0.116061,0.072100,0.609387,0.065757,0.116698
39,SHREECEM.NS,66.0,160.00,28.970000,33.0,0.034,0.072685,1.000000,0.695149,0.033499,0.083117
40,GRASIM.NS,32.0,10.00,13.670000,36.0,0.608,0.032825,0.059561,0.856151,0.037221,0.136364
41,TATASTEEL.NS,193.0,4.00,41.619998,280.0,1.252,0.221571,0.021944,0.562033,0.339950,0.196104
42,HEROMOTOCO.NS,307.0,150.00,61.040000,313.0,0.257,0.355217,0.937304,0.357677,0.380893,0.103803
43,M&M.NS,109.0,33.00,16.630000,86.0,0.448,0.123095,0.203762,0.825003,0.099256,0.121521
44,EICHERMOT.NS,99.0,70.00,34.870000,45.0,0.115,0.111372,0.435737,0.633063,0.048387,0.090631
45,IOC.NS,720.0,10.00,32.709998,669.0,0.781,0.839390,0.059561,0.655793,0.822581,0.152412
46,SBICARD.NS,42.0,2.50,10.980000,NaN,0.139,0.044549,0.012539,0.884458,NaN,0.092857
47,PIDILITIND.NS,68.0,10.00,41.650000,51.0,0.370,0.075029,0.059561,0.561717,0.055831,0.114286
48,DMART.NS,NaN,NaN,0.000000,NaN,0.196,NaN,NaN,1.000000,NaN,0.098145
49,HDFCAMC.NS,214.0,54.00,67.670000,171.0,-0.028,0.246190,0.335423,0.287909,0.204715,0.077365

In [10]:
weights = {
      "Dividend Yield(%) Normalised":0.2,
      "Dividend Rate Normalised":0.2,
      "Payout Ratio(%) Normalised":0.2,
      "5 Year Avg Dividend Yield(%) Normalised":0.2,
      "Earning Growth(%) Normalised":0.2
  }
dividend_df["Dividend Score"] = dividend_df[[col for col in weights.keys()]].mul(list(weights.values())).sum(axis=1)

In [12]:
dividend_df

,Ticker,Dividend Yield(%),Dividend Rate,Payout Ratio(%),5 Year Avg Dividend Yield(%),Earning Growth(%),Dividend Yield(%) Normalised,Dividend Rate Normalised,Payout Ratio(%) Normalised,5 Year Avg Dividend Yield(%) Normalised,Earning Growth(%) Normalised,Dividend Score
0,RELIANCE.NS,46.0,6.00,9.210000,44.0,-0.126,0.049238,0.034483,0.903083,0.047146,0.068275,0.220445
1,TCS.NS,564.0,124.00,46.320000,149.0,0.122,0.656506,0.774295,0.512575,0.177419,0.091280,0.442415
2,HDFCBANK.NS,174.0,13.00,21.760000,102.0,0.075,0.199297,0.078370,0.771020,0.119107,0.086920,0.250943
3,INFY.NS,418.0,50.00,64.650000,240.0,0.118,0.485346,0.310345,0.319689,0.290323,0.090909,0.299322
4,ICICIBANK.NS,87.0,11.00,14.710000,99.0,0.084,0.097304,0.065831,0.845207,0.115385,0.087755,0.242296
5,HINDUNILVR.NS,207.0,44.00,95.030000,158.0,0.214,0.237984,0.272727,0.000000,0.188586,0.099814,0.159822
6,SBIN.NS,177.0,17.35,17.440000,150.0,-0.031,0.202814,0.105643,0.816479,0.178660,0.077087,0.276136
7,BAJFINANCE.NS,62.0,5.40,14.420000,24.0,0.214,0.067995,0.030721,0.848258,0.022333,0.099814,0.213824
8,BHARTIARTL.NS,89.0,16.00,36.060002,80.0,-0.340,0.099648,0.097179,0.620541,0.091811,0.048423,0.191520
9,ITC.NS,570.0,16.00,86.920000,372.0,-0.727,0.663540,0.097179,0.085341,0.454094,0.012523,0.262536
10,KOTAKBANK.NS,13.0,0.50,2.580000,6.0,0.098,0.010551,0.000000,0.972851,0.000000,0.089054,0.214491
11,ADANIENT.NS,4.0,1.30,1.710000,65.0,NaN,0.000000,0.005016,0.982006,0.073201,NaN,0.212044
12,LT.NS,96.0,38.00,29.090000,91.0,-0.345,0.107855,0.235110,0.693886,0.105459,0.047959,0.238054
13,HCLTECH.NS,831.0,96.00,88.010000,357.0,-0.002,0.969519,0.598746,0.073871,0.435484,0.079777,0.431480
14,ASIANPAINT.NS,102.0,27.50,55.530000,87.0,0.693,0.114889,0.169279,0.415658,0.100496,0.144249,0.188914
15,AXISBANK.NS,8.0,1.00,1.180000,103.0,0.064,0.004689,0.003135,0.987583,0.120347,0.085900,0.240331
16,SUNPHARMA.NS,93.0,16.50,34.520000,93.0,0.256,0.104338,0.100313,0.636746,0.107940,0.103711,0.210610
17,WIPRO.NS,857.0,17.00,87.580000,151.0,-0.016,1.000000,0.103448,0.078396,0.179901,0.078479,0.288045
18,ULTRACEMCO.NS,71.0,77.50,27.930000,53.0,NaN,0.078546,0.482759,0.706093,0.058313,NaN,0.265142
19,HDFCLIFE.NS,37.0,2.10,23.700000,31.0,0.041,0.038687,0.010031,0.750605,0.031017,0.083766,0.182821
20,ONGC.NS,699.0,18.50,41.000000,511.0,0.478,0.814771,0.112853,0.568557,0.626551,0.124304,0.449407
21,NTPC.NS,310.0,11.35,29.070000,336.0,-0.016,0.358734,0.068025,0.694097,0.409429,0.078479,0.321753
22,POWERGRID.NS,429.0,12.25,44.750000,474.0,0.096,0.498242,0.073668,0.529096,0.580645,0.088868,0.354104
23,TATAMOTORS.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
24,INDUSINDBK.NS,17.0,1.50,0.000000,54.0,NaN,0.015240,0.006270,1.000000,0.059553,NaN,0.216213
25,ADANIGREEN.NS,NaN,NaN,0.000000,NaN,2.098,NaN,NaN,1.000000,NaN,0.274583,0.254917
26,TITAN.NS,26.0,11.00,19.229999,27.0,0.351,0.025791,0.065831,0.797643,0.026055,0.112523,0.205569
27,DIVISLAB.NS,45.0,30.00,31.010000,114.0,0.136,0.048066,0.184953,0.673682,0.133995,0.092579,0.226655
28,TECHM.NS,344.0,51.00,83.040000,232.0,0.159,0.398593,0.316614,0.126171,0.280397,0.094712,0.243298
29,MARUTI.NS,107.0,140.00,28.910000,80.0,-0.064,0.120750,0.874608,0.695780,0.091811,0.074026,0.371395
30,COALINDIA.NS,457.0,22.00,52.320000,812.0,0.129,0.531067,0.134796,0.449437,1.000000,0.091929,0.441446
31,BPCL.NS,678.0,20.00,37.200000,540.0,0.280,0.790152,0.122257,0.608545,0.662531,0.105937,0.457884
32,JSWSTEEL.NS,55.0,7.10,3.070000,98.0,9.918,0.059789,0.041379,0.967694,0.114144,1.000000,0.436601
33,DRREDDY.NS,63.0,8.00,15.560001,63.0,-0.862,0.069168,0.047022,0.836262,0.070720,0.000000,0.204634
34,BAJAJFINSV.NS,8.0,1.30,1.640000,14.0,0.057,0.004689,0.005016,0.982742,0.009926,0.085250,0.217525
35,ADANIPORTS.NS,41.0,7.50,12.020001,57.0,0.036,0.043376,0.043887,0.873514,0.063275,0.083302,0.221471
36,CIPLA.NS,93.0,13.00,27.080000,48.0,-0.546,0.104338,0.078370,0.715037,0.052109,0.029314,0.195834
37,BRITANNIA.NS,177.0,90.50,71.309996,172.0,0.211,0.202814,0.564263,0.249605,0.205955,0.099536,0.264435
38,HAVELLS.NS,103.0,12.00,37.120000,59.0,0.396,0.116061,0.072100,0.609387,0.065757,0.116698,0.196000
39,SHREECEM.NS,66.0,160.00,28.970000,33.0,0.034,0.072685,1.000000,0.695149,0.033499,0.083117,0.376890
40,GRASIM.NS,32.0,10.00,13.670000,36.0,0.608,0.032825,0.059561,0.856151,0.037221,0.136364,0.224424
41,TATASTEEL.NS,193.0,4.00,41.619998,280.0,1.252,0.221571,0.021944,0.562033,0.339950,0.196104,0.268320
42,HEROMOTOCO.NS,307.0,150.00,61.040000,313.0,0.257,0.355217,0.937304,0.357677,0.380893,0.103803,0.426979
43,M&M.NS,109.0,33.00,16.630000,86.0,0.448,0.123095,0.203762,0.825003,0.099256,0.121521,0.274527
44,EICHERMOT.NS,99.0,70.00,34.870000,45.0,0.115,0.111372,0.435737,0.633063,0.048387,0.090631,0.263838
45,IOC.NS,720.0,10.00,32.709998,669.0,0.781,0.839390,0.059561,0.655793,0.822581,0.152412,0.505947
46,SBICARD.NS,42.0,2.50,10.980000,NaN,0.139,0.044549,0.012539,0.884458,NaN,0.092857,0.206881
47,PIDILITIND.NS,68.0,10.00,41.650000,51.0,0.370,0.075029,0.059561,0.561717,0.055831,0.114286,0.173285
48,DMART.NS,NaN,NaN,0.000000,NaN,0.196,NaN,NaN,1.000000,NaN,0.098145,0.219629
49,HDFCAMC.NS,214.0,54.00,67.670000,171.0,-0.028,0.246190,0.335423,0.287909,0.204715,0.077365,0.230320

In [13]:
dividend_df= dividend_df.sort_values(by="Dividend Score",ascending= False)
dividend_df.head(10)

,Ticker,Dividend Yield(%),Dividend Rate,Payout Ratio(%),5 Year Avg Dividend Yield(%),Earning Growth(%),Dividend Yield(%) Normalised,Dividend Rate Normalised,Payout Ratio(%) Normalised,5 Year Avg Dividend Yield(%) Normalised,Earning Growth(%) Normalised,Dividend Score
45,IOC.NS,720.0,10.0,32.709998,669.0,0.781,0.839390,0.059561,0.655793,0.822581,0.152412,0.505947
31,BPCL.NS,678.0,20.0,37.200000,540.0,0.280,0.790152,0.122257,0.608545,0.662531,0.105937,0.457884
20,ONGC.NS,699.0,18.5,41.000000,511.0,0.478,0.814771,0.112853,0.568557,0.626551,0.124304,0.449407
1,TCS.NS,564.0,124.0,46.320000,149.0,0.122,0.656506,0.774295,0.512575,0.177419,0.091280,0.442415
30,COALINDIA.NS,457.0,22.0,52.320000,812.0,0.129,0.531067,0.134796,0.449437,1.000000,0.091929,0.441446
32,JSWSTEEL.NS,55.0,7.1,3.070000,98.0,9.918,0.059789,0.041379,0.967694,0.114144,1.000000,0.436601
13,HCLTECH.NS,831.0,96.0,88.010000,357.0,-0.002,0.969519,0.598746,0.073871,0.435484,0.079777,0.431480
42,HEROMOTOCO.NS,307.0,150.0,61.040000,313.0,0.257,0.355217,0.937304,0.357677,0.380893,0.103803,0.426979
39,SHREECEM.NS,66.0,160.0,28.970000,33.0,0.034,0.072685,1.000000,0.695149,0.033499,0.083117,0.376890
29,MARUTI.NS,107.0,140.0,28.910000,80.0,-0.064,0.120750,0.874608,0.695780,0.091811,0.074026,0.371395